Repository ovh-ux/ovh-module-emailpro, pull requests merged in 2018-07, with the labels that each got.

#38 chore(guides): fix fr guide url
  src/emailpro/emailpro.app.js
Labels: enhancement, quality check

#39 chore(bower):use the right registry
  .bowerrc
Labels: bug

#40 fix(disclaimer): remove unnecessary strippedContent tooltip
  src/emailpro/disclaimer/emailpro-disclaimer.html
Labels: bug

#43 chore: replace eslint-config-ovh by eslint-config-airbnb-base
  .editorconfig
  .eslintignore
  .eslintrc
  .eslintrc.json
  Gruntfile.js
  package-lock.json
  package.json
  src/emailpro/account/add/emailpro-account-add.controller.js
  src/emailpro/account/alias/emailpro-account-alias.controller.js
  src/emailpro/account/delegation/emailpro-account-delegation.controller.js
  src/emailpro/account/delegation/setting/emailpro-account-delegation-setting.controller.js
  src/emailpro/account/emailpro-account.controller.js
  src/emailpro/account/remove/emailpro-account-remove.controller.js
  src/emailpro/account/update/emailpro-account-update.controller.js
  src/emailpro/api/emailpro-api.service.js
  src/emailpro/components/filters/emailProFilters.js
  src/emailpro/disclaimer/emailpro-disclaimer.controller.js
  src/emailpro/domain/add/emailpro-domain-add.controller.js
  src/emailpro/domain/emailpro-domain.controller.js
  src/emailpro/domain/emailpro-domain.service.js
  src/emailpro/domain/mx-autoconfig/emailpro-domain-mx-autoconfig.controller.js
  src/emailpro/domain/remove/emailpro-domain-remove.controller.js
  src/emailpro/domain/srv-autoconfig/emailpro-domain-srv-autoconfig.controller.js
  src/emailpro/domain/update/emailpro-domain-update.controller.js
  src/emailpro/emailpro-controllers.module.js
  src/emailpro/emailpro-resource-services.module.js
  src/emailpro/emailpro-tabs-controller.js
  src/emailpro/emailpro-toolboxes.js
  src/emailpro/emailpro.app.js
  src/emailpro/emailpro.controller.js
  src/emailpro/emailpro.service.js
  src/emailpro/external-contact/emailpro-external-contact-tab.controller.js
  src/emailpro/external-contact/emailpro-external-contact.controller.js
  src/emailpro/external-contact/emailpro-external-contact.service.js
  src/emailpro/information/emailpro-information-tab.js
  src/emailpro/license/history/emailpro-license-history.js
  src/emailpro/password/emailpro-password.service.js
  src/emailpro/service/configure/emailpro-service-configure.js
  src/emailpro/task/emailpro-task.controller.js
  src/emailpro/update/renew/emailpro-update-renew.controller.js
Labels: enhancement

#44 chore(i18n): retrieve translations
  src/resources/i18n/emailpro/Messages_cs_CZ.xml
  src/resources/i18n/emailpro/Messages_en_ASIA.xml
  src/resources/i18n/emailpro/Messages_en_AU.xml
  src/resources/i18n/emailpro/Messages_en_CA.xml
  src/resources/i18n/emailpro/Messages_en_GB.xml
  src/resources/i18n/emailpro/Messages_en_SG.xml
  src/resources/i18n/emailpro/Messages_en_US.xml
  src/resources/i18n/emailpro/Messages_es_ES.xml
  src/resources/i18n/emailpro/Messages_es_US.xml
  src/resources/i18n/emailpro/Messages_fi_FI.xml
  src/resources/i18n/emailpro/Messages_it_IT.xml
  src/resources/i18n/emailpro/Messages_lt_LT.xml
  src/resources/i18n/emailpro/Messages_nl_NL.xml
  src/resources/i18n/emailpro/Messages_pl_PL.xml
Labels: enhancement

#55 fix(emailpro.dashboard): popover placement set right
  package-lock.json
  src/emailpro/information/emailpro-information.html
Labels: bug

#63 fix(account): improve progress label position
  package-lock.json
  src/emailpro/account/emailpro-account.html
Labels: bug

#62 fix(external-domain-nonauth): add unautoritative external domain name
  src/emailpro/domain/add/emailpro-domain-add.controller.js
  src/emailpro/domain/add/emailpro-domain-add.html
Labels: bug, quality check ok
