Repository ovh-ux/ovh-module-emailpro, pull requests merged in 2018-11, with the labels that each got.

#125 fix(signature) : ui controls alignment
  src/emailpro/disclaimer/add/emailpro-disclaimer-add.html
  src/emailpro/disclaimer/update/emailpro-disclaimer-update.html
Labels: bug, quality check ok

#133 Update readme
  README.md
Labels: enhancement

#135 fix(products): remove use of Products service
  package.json
  src/emailpro/domain/emailpro-domain.service.js
  src/emailpro/emailpro.service.js
  yarn.lock
Labels: :santa: one-manager, quality check ok

#126 refactor(components.string): move to webUniverseComponents
  src/emailpro/disclaimer/emailpro-disclaimer.html
  src/emailpro/disclaimer/remove/emailpro-disclaimer-remove.html
  src/emailpro/update/renew/emailpro-update-renew.html
Labels: :santa: one-manager, quality check ok

#129 refactor(components.validator): move to webUniverseComponents
  src/emailpro/domain/add/emailpro-domain-add.controller.js
  src/emailpro/domain/update/emailpro-domain-update.controller.js
Labels: :santa: one-manager, quality check ok

#127 refactor(components.loader): replace loader by oui-spinner
  src/emailpro/account/delegation/emailpro-account-delegation.html
  src/emailpro/account/emailpro-account.html
  src/emailpro/domain/emailpro-domain.html
  src/emailpro/external-contact/emailpro-external-contact.html
  src/emailpro/update/renew/emailpro-update-renew.html
Labels: :santa: one-manager, quality check ok

#141 fix: use the right WucApi service
  src/emailpro/api/emailpro-api.service.js
  src/emailpro/domain/emailpro-domain.html
  yarn.lock
Labels: bug, quality check ok

#103 refactor(emailpro.translations.domain): remove duplicates
  src/emailpro/translations/Messages_fr_FR.xml
Labels: enhancement

#150 fix(deps): upgrade npm-run-all to v4.1.5
  package.json
  yarn.lock
Labels: bug
