Repository ovh-ux/ovh-module-emailpro, pull requests merged in 2019-07, with the labels that each got.

#215 Fix/mx plan quota tasks
  src/emailpro/account/emailpro-account.controller.js
  src/emailpro/account/emailpro-account.html
  src/emailpro/account/emailpro-constants.js
  src/emailpro/account/update/emailpro-account-update.controller.js
  src/emailpro/account/update/emailpro-account-update.html
  src/emailpro/domain/emailpro-domain.html
  src/emailpro/emailpro.service.js
  src/emailpro/task/emailpro-task.constants.js
  src/emailpro/task/emailpro-task.controller.js
  src/emailpro/task/emailpro-task.html
  src/emailpro/translations/Messages_fr_FR.xml
Labels: enhancement, quality check ok, translation required

#221 fix(i18n): retrieve translations
  src/emailpro/translations/Messages_de_DE.xml
  src/emailpro/translations/Messages_en_ASIA.xml
  src/emailpro/translations/Messages_en_AU.xml
  src/emailpro/translations/Messages_en_CA.xml
  src/emailpro/translations/Messages_en_GB.xml
  src/emailpro/translations/Messages_en_SG.xml
  src/emailpro/translations/Messages_en_US.xml
  src/emailpro/translations/Messages_es_ES.xml
  src/emailpro/translations/Messages_it_IT.xml
  src/emailpro/translations/Messages_pl_PL.xml
Labels: bug

#222 Release v7.2.7
  package.json
  src/emailpro/account/emailpro-account.controller.js
  src/emailpro/account/emailpro-account.html
  src/emailpro/account/emailpro-constants.js
  src/emailpro/account/update/emailpro-account-update.controller.js
  src/emailpro/account/update/emailpro-account-update.html
  src/emailpro/domain/emailpro-domain.html
  src/emailpro/emailpro.service.js
  src/emailpro/task/emailpro-task.constants.js
  src/emailpro/task/emailpro-task.controller.js
  src/emailpro/task/emailpro-task.html
  src/emailpro/translations/Messages_cs_CZ.xml
  src/emailpro/translations/Messages_de_DE.xml
  src/emailpro/translations/Messages_en_ASIA.xml
  src/emailpro/translations/Messages_en_AU.xml
  src/emailpro/translations/Messages_en_CA.xml
  src/emailpro/translations/Messages_en_GB.xml
  src/emailpro/translations/Messages_en_SG.xml
  src/emailpro/translations/Messages_en_US.xml
  src/emailpro/translations/Messages_es_ES.xml
  src/emailpro/translations/Messages_es_US.xml
  src/emailpro/translations/Messages_fi_FI.xml
  src/emailpro/translations/Messages_fr_CA.xml
  src/emailpro/translations/Messages_fr_FR.xml
  src/emailpro/translations/Messages_it_IT.xml
  src/emailpro/translations/Messages_lt_LT.xml
  src/emailpro/translations/Messages_nl_NL.xml
  src/emailpro/translations/Messages_pl_PL.xml
  src/emailpro/translations/Messages_pt_PT.xml
  yarn.lock
Labels: release :package:

#225 fix(account): redirect to order when all accounts are configured
  src/emailpro/account/emailpro-account.controller.js
  src/emailpro/account/emailpro-account.html
  src/emailpro/account/emailpro-constants.js
  src/emailpro/translations/Messages_fr_FR.xml
Labels: bug, quality check ok

#227 Release v7.2.9
  src/emailpro/account/emailpro-account.controller.js
  src/emailpro/account/emailpro-account.html
  src/emailpro/account/emailpro-constants.js
  src/emailpro/translations/Messages_cs_CZ.xml
  src/emailpro/translations/Messages_de_DE.xml
  src/emailpro/translations/Messages_en_ASIA.xml
  src/emailpro/translations/Messages_en_AU.xml
  src/emailpro/translations/Messages_en_CA.xml
  src/emailpro/translations/Messages_en_GB.xml
  src/emailpro/translations/Messages_en_SG.xml
  src/emailpro/translations/Messages_en_US.xml
  src/emailpro/translations/Messages_es_ES.xml
  src/emailpro/translations/Messages_es_US.xml
  src/emailpro/translations/Messages_fi_FI.xml
  src/emailpro/translations/Messages_fr_CA.xml
  src/emailpro/translations/Messages_fr_FR.xml
  src/emailpro/translations/Messages_it_IT.xml
  src/emailpro/translations/Messages_lt_LT.xml
  src/emailpro/translations/Messages_nl_NL.xml
  src/emailpro/translations/Messages_pl_PL.xml
  src/emailpro/translations/Messages_pt_PT.xml
Labels: release :package:

#230 docs: generate changelog.md file
  CHANGELOG.md
Labels: documentation

#232 fix(emailpro.account): display modal to add account
  src/emailpro/account/emailpro-account.controller.js
Labels: bug, quality check ok
